        

    # def mission_one(self):
    #     self.telemetry_event.wait()
    #     self.telemetry_event.clear()
    #     self.send_command(lambda: self.set_flight_mode(0), priority=1) 
    #     time.sleep(1)
    #     self.send_command(lambda: self.arm_disarm(1), priority=1)  
    #     time.sleep(2)
    #     self.send_command(lambda: self.set_flight_mode(4), priority=1)  
    #     time.sleep(1)
    #     # self.send_command(lambda: self.set_flight_mode(0), priority=1)  
    #     # time.sleep(5)
    #     self.send_command(lambda: self.takeoff(4), priority=1) 
    #     time.sleep(6)
    #     # self.send_command(lambda: self.send_position(-10, 0, 0, 2, 0, 0), priority=1) 
    #     # time.sleep(8)
    #     self.send_command(lambda: self.send_position(-4, 0, 0, 0, 0, 0), priority=1) 
    #     time.sleep(4)
    #     # for i in range(5):
    #     #     self.send_command(lambda: self.navigate_to_target(), priority=1)
    #     #     time.sleep(2)
            
    #     self.send_command(lambda: self.send_position(0, 4, 0, 0, 0, 0), priority=1) 
    #     time.sleep(4)
    #     self.send_command(lambda: self.send_position(4, 0, 0, 0, 0, 0), priority=1) 
    #     time.sleep(4)
    #     self.send_command(lambda: self.send_position(0, -4, 0, 0, 0,0), priority=1) 
    #     time.sleep(4)
    #     self.send_command(lambda: self.set_flight_mode(8), priority=1)  
    #     time.sleep(4)
    #     # self.send_command(lambda: self.arm_disarm(0), priority=1)  

    # def testy(self):
    #     self.telemetry_event.wait()
    #     self.telemetry_event.clear()
    #     self.send_command(lambda: self.set_flight_mode(0), priority=1) 
    #     time.sleep(4)
    #     self.send_command(lambda: self.arm_disarm(1), priority=1)  
    #     time.sleep(4)
    #     self.send_command(lambda: self.set_flight_mode(4), priority=1)  
    #     time.sleep(10)
    #     self.send_command(lambda: self.takeoff(2), priority=1) 
    #     time.sleep(1)
    #     self.send_command(lambda: self.send_position(0, 5, 0, 0, 1, 0), priority=1) 
    #     time.sleep(1)
    #     self.send_command(lambda: self.set_flight_mode(6), priority=1)  
    #     time.sleep(6)
    #     self.send_command(lambda: self.arm_disarm(0), priority=1)  